default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: bootstrap_blog_development
test:
  <<: *default
  database: bootstrap_blog_test
production:
  <<: *default
  database: bootstrap_blog_production
  username: bootstrap_blog
  password: <%= ENV['BOOTSTRAP_BLOG_DATABASE_PASSWORD'] %>
